export type GalleryCategory = 'All' | 'Temples' | 'Sacred Places' | 'Book & Author';

export interface GalleryItem {
  id: string;
  plateNumber: string;
  title: string;
  subtitle: string;
  location: string;
  category: 'Temples' | 'Sacred Places' | 'Book & Author';
  description: string;
  imageUrl: string;
  thumbnailUrl?: string;
  aspectRatio: 'landscape' | 'portrait' | 'square';
  featuredInPreview?: boolean;
}

export const GALLERY_CATEGORIES: { id: GalleryCategory; label: string; count: number }[] = [
  { id: 'All', label: 'All Works', count: 18 },
  { id: 'Temples', label: 'Temples', count: 5 },
  { id: 'Sacred Places', label: 'Sacred Places', count: 5 },
  { id: 'Book & Author', label: 'Book & Author', count: 8 },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gallery-brihadeeswara',
    plateNumber: 'Plate I',
    title: 'Brihadeeswara Temple',
    subtitle: 'तञ्जावूरु बृहदीश्वर मन्दिर',
    location: 'Thanjavur, Tamil Nadu',
    category: 'Temples',
    description: 'The Great Living Chola Temple built entirely of interlocking granite with a monumental 216-foot Vimana and an 80-tonne monolithic cupola.',
    imageUrl: '/images/temples/brihadeeswara.webp',
    thumbnailUrl: '/images/temples/brihadeeswara-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: true,
  },
  {
    id: 'gallery-kashi',
    plateNumber: 'Plate II',
    title: 'Kashi Vishwanath & Ganga Ghats',
    subtitle: 'वाराणसी क्षेत्र • Moksha Puri',
    location: 'Varanasi, Uttar Pradesh',
    category: 'Sacred Places',
    description: 'The eternal sanctum of Shiva on the crescent bank of the holy Ganga, where dawn prayers and aarti resonate across millennia.',
    imageUrl: '/images/temples/kashi.webp',
    thumbnailUrl: '/images/temples/kashi-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: true,
  },
  {
    id: 'gallery-kedarnath',
    plateNumber: 'Plate III',
    title: 'Kedarnath Dham',
    subtitle: 'केदारनाथ धाम • Himalayan Tapasya',
    location: 'Garhwal Himalayas, Uttarakhand',
    category: 'Sacred Places',
    description: 'Perched at 3,583 meters amidst alpine glaciers in the Mandakini valley, Kedarnath represents the primordial pinnacle of ascetic devotion.',
    imageUrl: '/images/temples/kedarnath.webp',
    thumbnailUrl: '/images/temples/kedarnath-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: true,
  },
  {
    id: 'gallery-meenakshi',
    plateNumber: 'Plate IV',
    title: 'Madurai Meenakshi Amman',
    subtitle: 'मीनाक्षी सुन्दरेश्वर मन्दिर',
    location: 'Madurai, Tamil Nadu',
    category: 'Temples',
    description: 'Fourteen colossal sculptured Gopurams soaring above the ancient Vaigai riverbank, celebrating cosmic geometry and Agamic architecture.',
    imageUrl: '/images/temples/meenakshi.webp',
    thumbnailUrl: '/images/temples/meenakshi-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: true,
  },
  {
    id: 'gallery-book-launch',
    plateNumber: 'Plate V',
    title: 'Thirtha Yatra Book Release',
    subtitle: 'Official Launch with Revered Swamiji',
    location: 'Ramakrishna Math',
    category: 'Book & Author',
    description: 'Author Ramesh Gangashetty and esteemed monastic leaders unveiling the first copies of the Thirtha Yatra Guide.',
    imageUrl: '/images/journey/book-launch-ceremony.webp',
    aspectRatio: 'landscape',
    featuredInPreview: true,
  },
  {
    id: 'gallery-deepa-prajwalana',
    plateNumber: 'Plate VI',
    title: 'Ceremonial Deepa Prajwalana',
    subtitle: 'Lighting the Auspicious Brass Lamp',
    location: 'Sri Ramakrishna Sanctum',
    category: 'Book & Author',
    description: 'Author Ramesh Gangashetty initiating the book release with sacred oil lamp lighting before Sri Ramakrishna Paramahamsa.',
    imageUrl: '/images/journey/ceremonial-deepa-prajwalana.webp',
    aspectRatio: 'portrait',
    featuredInPreview: true,
  },
  {
    id: 'gallery-author-signing',
    plateNumber: 'Plate VII',
    title: 'First Edition Book Signing',
    subtitle: 'Dedication by Author Ramesh Gangashetty',
    location: 'Release Gathering',
    category: 'Book & Author',
    description: 'The author inscribing personal dedications for eager pilgrims and devotees attending the book consecration ceremony.',
    imageUrl: '/images/journey/author-book-signing.webp',
    aspectRatio: 'landscape',
    featuredInPreview: true,
  },
  {
    id: 'gallery-somnath',
    plateNumber: 'Plate VIII',
    title: 'Somnath Jyotirlinga',
    subtitle: 'सोमनाथ प्रभास पाटन • The Adya Jyotirlinga',
    location: 'Prabhas Patan, Gujarat Coast',
    category: 'Sacred Places',
    description: 'The first of the twelve sacred Jyotirlingas, standing resilient and majestic against the infinite horizon of the Arabian Sea.',
    imageUrl: '/images/temples/somnath.webp',
    thumbnailUrl: '/images/temples/somnath-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: true,
  },
  {
    id: 'gallery-tirupati',
    plateNumber: 'Plate IX',
    title: 'Tirupati Balaji (Tirumala)',
    subtitle: 'श्री वेंकटेश्वर स्वामी क्षेत्र',
    location: 'Seshachalam Hills, Andhra Pradesh',
    category: 'Temples',
    description: 'The sacred Seven Hills (Saptagiri) sanctuary crowned by the golden Ananda Nilayam vimana, reigning as Kaliyuga Vaikuntha.',
    imageUrl: '/images/temples/tirupati.webp',
    thumbnailUrl: '/images/temples/tirupati-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: false,
  },
  {
    id: 'gallery-padmanabhaswamy',
    plateNumber: 'Plate X',
    title: 'Sree Padmanabhaswamy Temple',
    subtitle: 'अनन्तपद्मनाभ स्वामी क्षेत्र',
    location: 'Thiruvananthapuram, Kerala',
    category: 'Temples',
    description: 'Historic Chera-Dravidian architecture facing the holy Padmatheertham tank, enshrining Lord Vishnu in eternal Ananta Shayana posture.',
    imageUrl: '/images/temples/padmanabhaswamy.webp',
    thumbnailUrl: '/images/temples/padmanabhaswamy-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: false,
  },
  {
    id: 'gallery-srirangam',
    plateNumber: 'Plate XI',
    title: 'Sri Ranganathaswamy Srirangam',
    subtitle: 'श्रीरङ्ग क्षेत्र • First Divya Desam',
    location: 'Trichy, Tamil Nadu',
    category: 'Temples',
    description: 'The colossal 156-acre sacred island kshetra nestled between the Kaveri and Kollidam rivers, adorned with 21 majestic gopurams.',
    imageUrl: '/images/temples/srirangam.webp',
    thumbnailUrl: '/images/temples/srirangam-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: false,
  },
  {
    id: 'gallery-murudeshwar',
    plateNumber: 'Plate XII',
    title: 'Murudeshwar Shiva Sanctuary',
    subtitle: 'मुरुडेश्वर क्षेत्र • Arabian Sea Cliff',
    location: 'Uttara Kannada Coast, Karnataka',
    category: 'Sacred Places',
    description: 'Spectacular seaside cliff sanctuary featuring the towering 123-foot Lord Shiva statue and the 20-storey Raja Gopuram.',
    imageUrl: '/images/temples/murudeshwar.webp',
    thumbnailUrl: '/images/temples/murudeshwar-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: false,
  },
  {
    id: 'gallery-rameswaram',
    plateNumber: 'Plate XIII',
    title: 'Rameshwaram Jyotirlinga',
    subtitle: 'रामेश्वर सेतु तीर्थ • 22 Theerthams',
    location: 'Rameswaram Island, Tamil Nadu',
    category: 'Sacred Places',
    description: 'Sacred island kshetra consecrated by Sri Rama, famed for the world’s longest sculptured pillared corridors and 22 holy wells.',
    imageUrl: '/images/temples/rameswaram.webp',
    thumbnailUrl: '/images/temples/rameswaram-thumb.webp',
    aspectRatio: 'landscape',
    featuredInPreview: false,
  },
  {
    id: 'gallery-swamiji-blessing',
    plateNumber: 'Plate XIV',
    title: 'Monastic Blessings & Benediction',
    subtitle: 'Sacred Guidance at Ramakrishna Math',
    location: 'Ramakrishna Math',
    category: 'Book & Author',
    description: 'Author Ramesh Gangashetty offering respectful pranam and receiving blessings from the revered Swamiji for the pilgrimage work.',
    imageUrl: '/images/journey/author-swamiji-blessing.webp',
    aspectRatio: 'portrait',
    featuredInPreview: false,
  },
  {
    id: 'gallery-math-altar',
    plateNumber: 'Plate XV',
    title: 'Ramakrishna Math Holy Altar',
    subtitle: 'Sanctum of Sri Ramakrishna & Holy Mother',
    location: 'Math Prayer Hall',
    category: 'Book & Author',
    description: 'The ornate carved wooden altar sanctifying the book release event with profound spiritual quietude and grace.',
    imageUrl: '/images/journey/ramakrishna-math-sanctum.webp',
    aspectRatio: 'landscape',
    featuredInPreview: false,
  },
  {
    id: 'gallery-invocation',
    plateNumber: 'Plate XVI',
    title: 'Invocatory Address & Prayer',
    subtitle: 'Opening Benediction by Dignitaries',
    location: 'Assembly Hall',
    category: 'Book & Author',
    description: 'Dignitaries and scholars addressing the gathering, praising the extensive research and field devotion behind Thirtha Yatra Guide.',
    imageUrl: '/images/journey/invocation-address.webp',
    aspectRatio: 'landscape',
    featuredInPreview: false,
  },
  {
    id: 'gallery-devotee-gathering',
    plateNumber: 'Plate XVII',
    title: 'Devotees & Spiritual Seekers',
    subtitle: 'Community of Pilgrimage Readers',
    location: 'Release Hall',
    category: 'Book & Author',
    description: 'Devotees, family members, and cultural enthusiasts gathered to receive their copies of the newly consecrated publication.',
    imageUrl: '/images/journey/pilgrim-devotee-gathering.webp',
    aspectRatio: 'landscape',
    featuredInPreview: false,
  },
  {
    id: 'gallery-assembly',
    plateNumber: 'Plate XVIII',
    title: 'Book Consecration Assembly',
    subtitle: 'Celebration of Literary & Spiritual Milestone',
    location: 'Release Dais',
    category: 'Book & Author',
    description: 'Author Ramesh Gangashetty, family, and esteemed guests gathered on the dais following the formal release of the guide.',
    imageUrl: '/images/journey/book-release-assembly.webp',
    aspectRatio: 'landscape',
    featuredInPreview: false,
  }
];

export const PREVIEW_GALLERY_ITEMS = GALLERY_ITEMS.filter((item) => item.featuredInPreview);
